### ISSUE TITLE
login not working

### ISSUE THREAD

**Issue by manelkdm** [manelkdm/kutt#27]
After creating the admin user and trying to login i only get "Welcome. Redirecting to homepage..." and get redirected to the login page. The user is created and i also get an error when entering a wrong password...

```
services:
  kutt:
    container_name: kutt
    image: kutt/kutt:main
    restart: unless-stopped
    volumes:
       - /docker/appdata/kutt:/var/lib/kutt
    environment:
      JWT_SECRET: "sdfsdf"
      DB_FILENAME: "/var/lib/kutt/data.sqlite"
    ports:
      - 3000:3000
```

![image](https://github.com/user-attachments/assets/6c0ea0c8-9cf3-4274-8781-2b0a8b739a7c)

_Originally from: https://github.com/thedevs-network/kutt/issues/
